server.port=${SERVER_PORT:8050}

#route import
spring.config.import=classpath:route.yml

# spring.cloud.gateway.routes

# TODO: URL ?? ??
eureka.client.service-url.defaultZone=http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@eureka.duri.asia/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# CORS
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=https://duri.asia
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true