spring:
  cloud:
    gateway:
      routes:
        - id: core-service
          uri: lb://DURI-CORE
          predicates:
            - Path=/api/**

        - id: auth-service
          uri: lb://DURI-AUTH
          predicates:
            - Path=/auth/**

        - id: front-service
          uri: lb://DURI-FRONT
          predicates:
            - Path=/**